### ISSUE TITLE
Display current PLZ and let me change it.

### ISSUE THREAD

**Issue by anonjum** [hack4vdb/anthill-backend#83] opened 2016-08-22 18:34 UTC
This drastically improves usability and user understanding.

Especially for those users entering the meetup page following a first email with info: Thomas is aktiv, join him. They have entered their plz up to 5 months ago and probably have no clue how we know where they are from.

**Comment by c3o** [comment] 2016-08-22 18:43
Duplicate of #45

**Closed as completed by c3o** 2016-08-22 18:43 UTC
